adoption/urls.py
from django.urls import path

from . import views

app_name = 'adoption'
urlpatterns = [
    path('', views.adoption_list, name='adopcion_list'),
    path('<int:id>/', views.adoption_detail, name = 'adopcion_detail'),
    path('solicitud/<int:pet_id>/', views.solicitud_adopcion, name = 'solicitud_adopcion'),
    path('gracias-por-adoptar/', views.gracias, name='gracias'),
    path('apadrinar/<int:pet_id>/', views.apadrinar, name='apadrinar'),
]

pets/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

from django.conf.urls.static import static


from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('contacto/',views.contacto, name='contacto'),
    path('maltrato-animal/',views.maltrato, name='maltrato'),
    path('veterinarias/',views.veterinarias_list, name='veterinaria_list'),
    path('gracias/',views.gracias, name='gracias'),
    path('perfil/', include('perfil.urls', namespace='perfil')),
    path('adopcion/', include('adoption.urls', namespace='adopcion')),
    path('voluntarios/', include('voluntario.urls', namespace='voluntario')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

 

adoption/models.py
from django.db import models

from django.contrib.auth.models import User
from perfil.models import Perfil



usuarios = ['camilo','kevin','paola','german']


class Tipo_Pet(models.Model):
    '''type pet if: cat or dog'''

    tipo_pet = models.CharField(max_length=200) 

    def __str__(self):
        return self.tipo_pet


class Sexo(models.Model):
    """pet sex"""
    sexo = models.CharField(max_length=100)

    def __str__(self):
        return self.sexo
    

class Raza(models.Model):
    '''pet raza'''
    raza = models.CharField(max_length=100)
    
    def __str__(self):
        return self.raza

class Color(models.Model):
    '''pet color'''
    color = models.CharField(max_length=100)

    def __str__(self):
        return self.color

class Esterilizado(models.Model):
    '''pet esterilization 1=si 0=no'''
    esterilizado = models.CharField(max_length=2)

    def __str__(self):
        return self.esterilizado

class Tamano(models.Model):
    '''pet size'''

    tamano = models.CharField(max_length=50)

    def __str__(self):
        return self.tamano


class Estado_Adopcion(models.Model):
    '''pet status ej: Adopted, in adoption'''

    estado = models.CharField(max_length=100)

    def __str__(self):
        return self.estado

class Ubicacion(models.Model):
    '''pet ubication'''

    ubicacion = models.CharField(max_length=255)

    def __str__(self):
        return self.ubicacion

class Vacuna(models.Model):
    '''vacuna pet'''
    vacuna = models.CharField(max_length=50)
    

    def __str__(self):
        return self.vacuna

class Desparasitado(models.Model):
    
    desparasitado = models.CharField(max_length=50)
    

    def __str__(self):
        return self.desparasitado


class Salud(models.Model):

    estado_salud = models.CharField(max_length=100)
    

    def __str__(self):
        return self.estado_salud

class Cuidados(models.Model):

    nombre_cuidado = models.CharField(max_length=255)
    descripcion_cuidado = models.TextField()

    def __str__(self):
        return self.nombre_cuidado

class Pet(models.Model):
    nombre = models.CharField(max_length=100, verbose_name='Nombre de la Mascota')
    edad = models.IntegerField(help_text='Meses')
    historia = models.TextField()
    imagen_destacada = models.ImageField(upload_to='images/adoption/')
    imagen1 = models.ImageField(upload_to='images/adoption/',blank=True,null=True)
    imagen2 = models.ImageField(upload_to='images/adoption/',blank=True,null=True)
    fecha_publicacion = models.DateField(auto_now_add=True)
    tipo_pet = models.ForeignKey(Tipo_Pet, on_delete=models.CASCADE)
    tamano = models.ForeignKey(Tamano, on_delete=models.CASCADE)
    raza = models.ForeignKey(Raza, on_delete=models.CASCADE)
    sexo = models.ForeignKey(Sexo, on_delete=models.CASCADE, null=True)
    color = models.ForeignKey(Color, on_delete=models.CASCADE)
    esterilizado = models.ForeignKey(Esterilizado, on_delete=models.CASCADE)
    vacunado = models.ForeignKey(Vacuna, on_delete=models.CASCADE, null=True)
    desparasitado = models.ForeignKey(Desparasitado, on_delete=models.CASCADE, null=True)
    chip = models.CharField(max_length=10, null=True,blank=True)
    ubicacion = models.ForeignKey(Ubicacion, on_delete=models.CASCADE)
    estado_adopcion = models.ForeignKey(Estado_Adopcion, on_delete=models.CASCADE, null=True)
    estado_salud = models.ForeignKey(Salud, on_delete=models.Model, null=True)
    cuidados_especiales = models.ForeignKey(Cuidados, on_delete=models.Model, null=True)
    #usuario = models.ForeignKey(User,null=True,blank=True)
    usuario = usuarios[0]

    def __str__(self):
        return self.nombre




class Solicitud_Adopcion(models.Model):
    '''solicitudes de adopcion enviadas por el formulario'''

    pet = models.ForeignKey(Pet, on_delete=models.CASCADE)
    perfil = models.ForeignKey(Perfil, on_delete=models.CASCADE)
    fecha_solicitud = models.DateField(auto_now_add=True)
    estado_solicitud = models.BooleanField(blank=True, default=False)
    comentarios_solicitud = models.TextField(blank=True)

    def __str__(self):
        return self.fecha_solicitud

adoption/forms.py
from django import forms
from django.contrib.auth.models import User

from perfil.models import Perfil



class AdopcionForm(forms.Form):
    '''formulario para postular la adopcion de un peludo'''
    
    rut = forms.CharField(label='Rut:', max_length=10)
    nombres = forms.CharField(label='Nombres:', max_length=100)
    apellidos = forms.CharField(label='Apellidos:', max_length=100)
    email = forms.EmailField(label='Email:')
    direccion = forms.CharField(label='Dirección de residencia:', max_length=255)
    fecha_nacimiento = forms.DateField(label='Fecha de nacimiento:')
    telefono_fijo = forms.CharField(label='Telefono fijo', max_length=20)
    telefono_celular = forms.CharField(label='Telefono celular', max_length=20)
    

adoption/views.py
from django.shortcuts import render, redirect
from django.urls import reverse

from perfil.models import Perfil
from django.contrib.auth.models import User

from .models import Pet, Solicitud_Adopcion

from .forms import AdopcionForm


def adoption_list(request):
    '''list pets actives for adoption'''

    #pets_adoption = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]
    pets_adoption = Pet.objects.filter(estado_adopcion = 1)
    context = {
        'pets_adoption':pets_adoption
    }
    return render(request, 'adoption/adoption_list.html', context)



def adoption_detail(request, id):
    '''detail pet in adoption'''

    pet = Pet.objects.get(id=id)
    context = {
        'pet':pet
    }
    return render(request, 'adoption/adoption_detail.html', context)




def solicitud_adopcion(request, pet_id):
    '''solucitud de adopcion del peludo'''
    pet = Pet.objects.get(id=pet_id)
    if request.method == 'POST':
        print('ingresa a method = post')
        form = AdopcionForm(request.POST)
        if form.is_valid():
            print('form is valid')
            rut = form.cleaned_data['rut']
            nombres = form.cleaned_data['nombres']
            apellidos = form.cleaned_data['apellidos']
            email = form.cleaned_data['email']
            direccion = form.cleaned_data['direccion']
            fecha_nacimiento = form.cleaned_data['fecha_nacimiento']
            telefono_fijo = form.cleaned_data['telefono_fijo']
            telefono_celular = form.cleaned_data['telefono_celular']

            
            
            if not Perfil.objects.filter(rut=rut).exists():
                print('perfil no existe.... se crea uno nuevo')
                user = User.objects.create(username=email, password='password1234567890',email=email, first_name=nombres,last_name=apellidos)
                user.save()
                perfil = Perfil.objects.get(user=user)
                perfil.rut = rut 
                perfil.direccion = direccion
                perfil.fecha_nacimiento = fecha_nacimiento
                perfil.telefono_fijo = telefono_fijo
                perfil.telefono_movil = telefono_celular
                perfil.save()
                print('se crea el perfil con exito')
                solicitud = Solicitud_Adopcion.objects.create(pet=pet, perfil=perfil)
                solicitud.save()
                print('se crea la solicitud en la bd')
            else:
                print(f'el perfil de ya existe..')
                perfil = Perfil.objects.get(rut=rut)
                solicitud = Solicitud_Adopcion.objects.create(pet=pet, perfil=perfil)
                solicitud.save()
                print('solicitud creada')

                

            print(f'el peludo se llama {pet.nombre}')
            return redirect('adoption:gracias')


    else:
        form = AdopcionForm()

    return render(request, 'adoption/adopcion_form.html', {'form':form, 'pet':pet})




def gracias(request):
    pass
    return render(request,'adoption/adopcion_gracias.html')



def apadrinar(request,pet_id):
    '''apadrinar un peludo'''

    pet = Pet.objects.get(id=pet_id)
    plans = {
        'bronce':{
            'valor':20000,
            'beneficio':'Cubre un mes de comida para un perro',
            'tiempo':'mensual'
        },
        'silver':{
            'valor':40000,
            'beneficio':'Cubre un mes de comida e insumos veterinarios',
            'tiempo':'mensual'
        },
        'gold':{
            'valor':60000,
            'beneficio':'Cubre la alimentación, atención e insumos veterinarios',
            'tiempo':'mensual'
        },
        'platinum':{
            'valor':80000,
            'beneficio':'Cubre el gasto total en salud, refugio y alimentación de un perro',
            'tiempo':'mensual'
        }
    }        
            
    context = {
        'pet':pet,
        'plans':plans
    }
    return render(request,'adoption/apadrinar_detail.html',context)

templates/adoption/adopcion_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <form class="mt-4" method="POST" >
        {% csrf_token %}
        {{ form.non_field_errors }}

        <h1 class="text-secondary text-center">Formulario de adopción de  {{pet.nombre|title}}</h1>
        <img src="/media/{{pet.imagen_destacada}}" class="img-thumbnail mx-auto d-block imagen-formulario-adopcion mb-4" alt="{{pet.nombre}}">
      
        
        <div class="form-group">
            <label for="rut">Rut</label>
            <input type="text" class="form-control" id="rut" name = 'rut' aria-describedby="textHelp" required>
            <small id="rutHelp" class="form-text text-muted">Ejemplo: 25000000-6</small>
        </div>
        <div class="form-group">
            <label for="nombres">Nombres</label>
            <input type="text" class="form-control" id="nombres" name = 'nombres' required>
        </div>
        <div class="form-group">
            <label for="apellidos">Apellidos</label>
            <input type="text" class="form-control" id="apellidos" name = 'apellidos' required>
        </div>
        <div class="form-group">
            <label for="email">Email</label>
            <input type="email" class="form-control" name = 'email' id="email" aria-describedby="emailHelp" placeholder="name@example.com" required>
        </div>
        <div class="form-group">
            <label for="direccion">Direccion</label>
            <input type="text" class="form-control" id="direccion" name = 'direccion' required>
        </div>
        <div class="form-group">
            <label for="fecha_nacimiento">Fecha de Nacimiento</label>
            <input type="date" class="form-control" id="fecha_nacimiento" name = 'fecha_nacimiento' required>
        </div>
        <div class="form-group">
            <label for="telefono_fijo">Teléfono Fijo</label>
            <input type="text" class="form-control" id="telefono_fijo" name = 'telefono_fijo' required>
        </div>
        <div class="form-group">
            <label for="telefono_celular">Teléfono Celular</label>
            <input type="text" class="form-control" id="telefono_celular" name = 'telefono_celular' required>
        </div>
        <button type="submit" class="btn btn-primary">Enviar Solicitud de Adopción</button>
    </form>

</div>

{% endblock %}

templates/adoption/adopcion_gracias.html
{% extends 'base.html' %}

{% block content %}
    {% load static %}
    
    <div class="alert alert-success mt-4" role="alert">
        <h4 class="alert-heading text-center">Gracias por adoptar!</h4>
        <p>Tu solicitud de adopción se ha enviado correctamente, nuestro equipo evaluará los datos suministrados y nos pondremos en contacto contigo para dar respuesta a la solicitud. </p>
        <hr>
        <p class="mb-0">Nuevamente te damos las gracias por querer ayudar a nuestros peludos...</p>
    </div>
    <div class="imagen text-center">
        <img src="{% static 'images/gracias.gif'%}" class="img-fluid mx-auto" alt="Responsive image">
    </div>
    
{% endblock %}

templates/adoption/adoption_detail.html
{% extends 'base.html'%}
{% block title %}|{{pet.nombre|title}}{%endblock%}
{% block content %}
    <div class="card text-center m-5">
        <div class="card-header">
            {{pet.estado_adopcion}}
        </div>
        <div class="card-body">
        <h3 class="card-title mb-3">{{pet.nombre|title}}</h3>
        <img src="/media/{{pet.imagen_destacada}}" class="img-fluid img-thumbnail" alt="{{pet.nombre}}">
        <p class="card-text text-left mt-4">{{pet.historia}}</p>
        <div id="contenedor-ul-car-detail">
            <h5 class="card-text m-4 ">Información Básica: </h5>
                <ul class="list-group list-group-flush text-left" id='list-basic-info'>
                    <li class="list-group-item">Edad: {{pet.edad}} Meses</li> 
                    <li class="list-group-item">Raza: {{pet.raza}}</li> 
                    <li class="list-group-item">Tamaño: {{pet.tamano}}</li>
                    <li class="list-group-item">Sexo: {{pet.sexo}}</li>
                    <li class="list-group-item">Color: {{pet.color}}</li>
                    <li class="list-group-item">Esterilizado: {{pet.esterilizado}}</li>
                    <li class="list-group-item">Vacunado: {{pet.vacunado}}</li>
                    <li class="list-group-item">Esterilizado: {{pet.esterilizado}}</li>
                    <li class="list-group-item">No. Chip: {{pet.chip}}</li>
                    <li class="list-group-item">Estado Salud: {{pet.estado_salud}}</li>
                    <li class="list-group-item">Ubicación: {{pet.ubicacion}}</li>
                    <li class="list-group-item">Cuidados Especiales: {{pet.cuidados_especiales}}</li>
                </ul>
        </div>
        <a href="#" class="btn btn-success m-4" data-toggle="modal" data-target="#exampleModal">Adoptar a {{pet.nombre|title}}</a>
        <a href="#" class="btn btn-warning m-4" data-toggle="modal" data-target="#apadrinarModal">Apadrinar a {{pet.nombre|title}}</a>
        </div>
        <div class="card-footer text-muted">
            Publicado en {{pet.fecha_publicacion}}
        </div>
    </div>
    <div class="boton-lista">
        <a class="btn btn-info" href="{% url 'adoption:adopcion_list'%}">Regresar a la lista</a>
    </div>

{% endblock%}


{% block modal %}

  <!-- Modal requisitos adopcion -->
  <div class="modal fade" id="exampleModal" data-backdrop="static" data-keyboard="false" tabindex="-1" role="dialog" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="staticBackdropLabel">Requisitos para adoptar</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <ul>
            <li>Ser mayor de edad.</li>
            <li>Aceptar seguimiento de adopción.</li>
            <li>La persona en firmar será el responsable del adoptado.</li>
            <li>Casa con sitio cerrado para evitar escapes.</li>
            <li>Firmar contrato de adopción.</li>
            <li>Castración o esterilización ineludible si no esta operado.</li>
            <li>Disponer de un lugar limpio y abrigado.</li>
            <li>Alimentación adecuada y atención veterinaria correspondiente.</li>
            <li>Devolución inmediata si no puede cumplir con la responsabilidad de tenencia responsable.</li>
            <li>Consulte su bolsillo antes de adoptar.</li>
            <li>Entrevista pre-adopción.</li>
          </ul>
          <p class="alert alert-warning">Si cumple con los ateriores requisitos de clic en "Aceptar y Continuar", de lo contrario seleccione "Cerrar"</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
          <a href="{% url 'adopcion:solicitud_adopcion' pet.id %}" type="button" class="btn btn-success">Aceptar y Continuar</a>
        </div>       
      </div>
    </div>
  </div>



{% endblock %}

templates/adoption/adoption_list.html
{% extends 'base.html'%}

{% block title%}|Adopción{%endblock%}

{% block content %}
    <h1 class="text-center pt-4 mb-5">Peludos en Adopción</h1>

    
        <div class="row justify-content-center">
            {% for pet in pets_adoption %}
            <div class="col-sm-12 col-md-5 col-lg-3 m-2">
                <div class="card m-auto" style="width: 18rem; ">
                    <img src="/media/{{pet.imagen_destacada}}" class="card-img-top rounded" alt="{{pet.nombre}}">
                    <div class="card-body text-center">
                    <h5 class="card-title">{{pet.nombre|title}}</h5>
                    <a href="{{pet.id}}" class="btn btn-info">Conoce mi historia</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    





{% endblock %}

templates/adoption/apadrinar_detail.html
{% extends 'base.html'%}
{% block title %}Apadrinar a {{pet.nombre}}{%endblock%}

{% block content %}
    <div class="padrino-info">
        <h2>¿EN QUÉ CONSISTE SER MADRINA O PADRINO?</h2>
            <p>Inscribiéndote como madrina o padrino en Fundación Huella Animal estarás ayudando a nuestros rescatados a cubrir sus gastos en hogar, comida y salud.</p>
            
            <p>Los padrinos y madrinas son personas que se comprometen a aportar mensualmente una cantidad de dinero a uno de nuestros rescatados.</p>
            
            <p>De esta manera, como bien dice el nombre, la persona “apadrina” al rescatado para ayudarle a mantenerse sano y feliz. Esta modalidad es similar a los Socios.</p>
    </div>
    <div class="padrino-info">
        <h2>¿POR QUÉ SER MADRINA O PADRINO?</h2>
        <p>Para nuestra fundación el aporte de los padrinos es fundamental, ya que sus contribuciones nos permiten asegurar la alimentación y salud de uno de nuestros rescatados.</p>
    </div>
    <div class="padrino-info">
        <h2>¿CÓMO ME HAGO PADRINO O MADRINA?</h2>
        <p>Para ser socio sólo debes realizar estos tres pasos:

            Escoge a uno de los rescatados en busca de padrinos más abajo.
            Escoge uno de las cuatro modalidades de padrino: Bronce ($20.000), Silver ($40.000), Gold ($60.000) y Platinum ($80.000).
            Selecciona la modalidad y serás redirigido a la página de pago para efectuar la transferencia.</p>
    </div>


    <div class="planes">
        {% for key, value in plans.items %}
            <div class="plan-info">
                {{key}}
                {% for k,v in value.items %}
                    {{k}}{{v}}
                {% endfor %}
            </div>
        {% endfor %}
    </div>


{% endblock%}


{% block modal %}

<!-- Modal requisitos adopcion -->
<div class="modal fade" id="exampleModal" data-backdrop="static" data-keyboard="false" tabindex="-1" role="dialog" aria-labelledby="staticBackdropLabel" aria-hidden="true">
<div class="modal-dialog modal-dialog-centered">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title" id="staticBackdropLabel">Requisitos para adoptar</h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
      <ul>
        <li>Ser mayor de edad.</li>
        <li>Aceptar seguimiento de adopción.</li>
        <li>La persona en firmar será el responsable del adoptado.</li>
        <li>Casa con sitio cerrado para evitar escapes.</li>
        <li>Firmar contrato de adopción.</li>
        <li>Castración o esterilización ineludible si no esta operado.</li>
        <li>Disponer de un lugar limpio y abrigado.</li>
        <li>Alimentación adecuada y atención veterinaria correspondiente.</li>
        <li>Devolución inmediata si no puede cumplir con la responsabilidad de tenencia responsable.</li>
        <li>Consulte su bolsillo antes de adoptar.</li>
        <li>Entrevista pre-adopción.</li>
      </ul>
      <p class="alert alert-warning">Si cumple con los ateriores requisitos de clic en "Aceptar y Continuar", de lo contrario seleccione "Cerrar"</p>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
      <a href="{% url 'adopcion:solicitud_adopcion' pet.id %}" type="button" class="btn btn-success">Aceptar y Continuar</a>
    </div>       
  </div>
</div>
</div>



{% endblock %}