pets/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

from django.conf.urls.static import static


from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('contacto/',views.contacto, name='contacto'),
    path('maltrato-animal/',views.maltrato, name='maltrato'),
    path('veterinarias/',views.veterinarias_list, name='veterinaria_list'),
    path('gracias/',views.gracias, name='gracias'),
    path('perfil/', include('perfil.urls', namespace='perfil')),
    path('adopcion/', include('adoption.urls', namespace='adopcion')),
    path('voluntarios/', include('voluntario.urls', namespace='voluntario')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

 

voluntario/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings




from . import views

app_name = 'voluntario'
urlpatterns = [
    path('', views.home, name='home'),
    path('solicitud/', views.solicitud_voluntariado, name='solicitud_voluntariado'),
    
] 

 

voluntario/models.py
from django.db import models

from perfil.models import Perfil
from adoption.models import Tipo_Pet
from donacion.models import Tipo_Donacion
from evento.models import Tipo_Evento

# Create your models here.

class Casa_Temporal(Tipo_Pet):
    '''tipo mascota que puede acoger'''
    class Meta:
        proxy = True

class Otras_actividades(models.Model):
    '''otras actividades que se pueda colavorar'''

    nombre_actividad = models.CharField(max_length=255)
    descripcion_actividad = models.CharField(max_length=255)

    def __str__(self):
        return self.nombre_actividad


class Actividades_Voluntario(models.Model):
    perfil = models.ForeignKey(Perfil, on_delete=models.CASCADE, null=True)
    casa_temporal = models.ManyToManyField(Casa_Temporal,blank=True)
    donaciones = models.ManyToManyField(Tipo_Donacion,blank=True)
    eventos = models.ManyToManyField(Tipo_Evento, blank=True)
    otras_actividades = models.ManyToManyField(Otras_actividades, blank=True)
    experiencia = models.TextField(verbose_name='Experiencia',blank=True)
    extra = models.TextField(verbose_name='Sugerencia',blank=True)
   
    def __str__(self):
        return self.perfil.user.username




class Solicitud_Voluntario(models.Model):
    '''solicitudes para ser voluntario'''

    perfil = models.ForeignKey(Perfil, on_delete=models.CASCADE)
    actividades = models.ForeignKey(Actividades_Voluntario, on_delete=models.CASCADE)
    fecha_solicitud = models.DateField(auto_now_add=True)

    

voluntario/forms.py
from django import forms
from voluntario.models import Casa_Temporal, Otras_actividades
from donacion.models import Tipo_Donacion
from evento.models import Tipo_Evento



class InscripcionVoluntarioForm(forms.Form):
    '''formulario para solicitudes de inscripcion de voluntarios'''

    rut = forms.CharField(label='Rut:', max_length=10)
    nombres = forms.CharField(label='Nombres:', max_length=100)
    apellidos = forms.CharField(label='Apellidos:', max_length=100)
    email = forms.EmailField(label='Email:')
    direccion = forms.CharField(label='Dirección de residencia:', max_length=255)
    fecha_nacimiento = forms.DateField(label='Fecha de nacimiento:')
    telefono_fijo = forms.CharField(label='Telefono fijo', max_length=20)
    telefono_celular = forms.CharField(label='Telefono celular', max_length=20)
    ##obciones de voluntariado
    casa_temporal = forms.ModelMultipleChoiceField(queryset=Casa_Temporal.objects.all())
    donaciones = forms.ModelMultipleChoiceField(queryset=Tipo_Donacion.objects.all())
    eventos = forms.ModelMultipleChoiceField(queryset=Tipo_Evento.objects.all())
    otras_actividades = forms.ModelMultipleChoiceField(queryset=Otras_actividades.objects.all())
    experiencia = forms.CharField()
    extra = forms.CharField()

voluntario/views.py
from django.shortcuts import render, redirect

from perfil.models import Perfil
from django.contrib.auth.models import User

from .forms import InscripcionVoluntarioForm

from voluntario.models import Actividades_Voluntario, Solicitud_Voluntario

# Create your views here.
def home(request):
    '''home page voluntario info'''

    return render(request,'voluntarios/voluntario_home.html')



def solicitud_voluntariado(request):
    '''tramitar la solicitud de voluntariado'''

    if request.method == 'POST':

        form = InscripcionVoluntarioForm(request.POST)
        print('se crea el form de post')
        if form.is_valid():
            print('formulario es valido')
            rut = form.cleaned_data['rut']
            nombres = form.cleaned_data['nombres']
            apellidos = form.cleaned_data['apellidos']
            email = form.cleaned_data['email']
            direccion = form.cleaned_data['direccion']
            fecha_nacimiento = form.cleaned_data['fecha_nacimiento']
            telefono_fijo = form.cleaned_data['telefono_fijo']
            telefono_celular = form.cleaned_data['telefono_celular']
            casa_temporal = form.cleaned_data['casa_temporal']
            donaciones = form.cleaned_data['donaciones']
            eventos = form.cleaned_data['eventos']
            otras_actividades = form.cleaned_data['otras_actividades']
            experiencia = form.cleaned_data['experiencia']
            extra = form.cleaned_data['extra']

            if not Perfil.objects.filter(rut=rut): #no existe perfil
                user = User.objects.create(username=email,first_name=nombres, last_name=apellidos, email=email)
                user.save()
                print('usuario creado')
                perfil = Perfil.objects.get(user=user)
                perfil.rut = rut
                perfil.direccion = direccion
                perfil.fecha_nacimiento = fecha_nacimiento
                perfil.telefono_fijo = telefono_fijo
                perfil.telefono_movil = telefono_celular
                perfil.save()
                print('guardamos el perfil con los nuevos datos')
                #asigno las actividades al perfil
                actividades = Actividades_Voluntario.objects.create(perfil=perfil,experiencia=experiencia, extra=extra)
                actividades.save()
                print('actividades creadas OK')
                
                for item in casa_temporal:
                    actividades.casa_temporal.add(item)
                
                for item in donaciones:
                    actividades.donaciones.add(item)

                for item in eventos:
                    actividades.eventos.add(item)

                for item in otras_actividades:
                    actividades.otras_actividades.add(item)
                
                actividades.save()
                
                #creamos la soplicitud_voluntariado
                solicitud = Solicitud_Voluntario.objects.create(perfil=perfil, actividades=actividades)
                return redirect('/gracias/')

            else:
                print('perfil ya existe') #perfil existe
                perfil = Perfil.objects.get(rut=rut)
                actividades = Actividades_Voluntario.objects.create(perfil=perfil,experiencia=experiencia, extra=extra)
                print('actividades creadas OK')
                for item in casa_temporal:
                    actividades.casa_temporal.add(item)
                
                for item in donaciones:
                    actividades.donaciones.add(item)

                for item in eventos:
                    actividades.eventos.add(item)

                for item in otras_actividades:
                    actividades.otras_actividades.add(item)
                
                actividades.save()
                print('items actividades agregados')
                #creamos la soplicitud_voluntariado
                solicitud = Solicitud_Voluntario.objects.create(perfil=perfil, actividades=actividades)
                print('solicitud creada con exito')

                return redirect('/gracias/')

    else:

        form = InscripcionVoluntarioForm()

    return render(request,'voluntarios/voluntario_form.html',{'form':form})

templates/voluntarios/voluntario_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <form class="mt-4" method="POST" >
        {% csrf_token %}
        
        <h1 class="text-secondary text-center mb-4">Formulario de inscripción de voluntariado</h1>
        <h4 class="text-secondary m-4">Datos Personales</h4>
        <div class="form-group">
            <label for="rut">Rut</label>
            <input type="text" class="form-control" id="rut" name = 'rut' aria-describedby="textHelp" required>
            <small id="rutHelp" class="form-text text-muted">Ejemplo: 25000000-6</small>
        </div>
        <div class="form-group">
            <label for="nombres">Nombres</label>
            <input type="text" class="form-control" id="nombres" name = 'nombres' required>
        </div>
        <div class="form-group">
            <label for="apellidos">Apellidos</label>
            <input type="text" class="form-control" id="apellidos" name = 'apellidos' required>
        </div>
        <div class="form-group">
            <label for="email">Email</label>
            <input type="email" class="form-control" name = 'email' id="email" aria-describedby="emailHelp" placeholder="name@example.com" required>
        </div>
        <div class="form-group">
            <label for="direccion">Direccion</label>
            <input type="text" class="form-control" id="direccion" name = 'direccion' required>
        </div>
        <div class="form-group">
            <label for="fecha_nacimiento">Fecha de Nacimiento</label>
            <input type="date" class="form-control" id="fecha_nacimiento" name = 'fecha_nacimiento' required>
        </div>
        <div class="form-group">
            <label for="telefono_fijo">Teléfono Fijo</label>
            <input type="text" class="form-control" id="telefono_fijo" name = 'telefono_fijo' required>
        </div>
        <div class="form-group">
            <label for="telefono_celular">Teléfono Celular</label>
            <input type="text" class="form-control" id="telefono_celular" name = 'telefono_celular' required>
        </div>

        <div class="contenedor-checkbox-voluntario mt-4">
            <h4 class="text-secondary m-4 text-center">Como voluntario puedo ayudar con:</h4>
            <div class="row mt-2">
                <div class="col-sm-12 col-md-6 col-lg-4 ">
                    <div class="contenedor-campos-individuales">
                        <div class="form-group">
                            <label for="casa_temporal" class="text-info">Casa Temporal</label>
                            <select multiple class="form-control" id="casa_temporal" name="casa_temporal">
                                {% for tipo_mascota in form.casa_temporal %}
                                    <option>{{tipo_mascota}}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                </div>
                <div class="col-sm-12 col-md-6 col-lg-4 ">
                    <div class="contenedor-campos-individuales">
                        <div class="form-group">
                            <label for="donaciones" class="text-info">Donaciones</label>
                            <select multiple class="form-control" id="donaciones" name="donaciones">
                                {% for donacion in form.donaciones %}
                                    <option>{{donacion}}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                </div>
                <div class="col-sm-12 col-md-6 col-lg-4 ">
                    <div class="contenedor-campos-individuales">
                        <div class="form-group">
                            <label for="eventos" class="text-info">Eventos</label>
                            <select multiple class="form-control" id="eventos" name="eventos">
                                {% for evento in form.eventos %}
                                    <option>{{evento}}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="row mt-2">
                <div class="col-sm-12 col-md-6 col-lg-4">
                    <div class="contenedor-campos-individuales ">
                        <div class="form-group">
                            <label for="otras_actividades" class="text-info">Otras Actividades</label>
                            <select multiple class="form-control" id="otras_actividades" name="otras_actividades">
                                {% for actividad in form.otras_actividades %}
                                    <option>{{actividad}}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row mt-2">
                <div class="col">
                    <div class="form-group">
                        <label for="exampleFormControlTextarea1">Tienes Experiencia?</label>
                        <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="experiencia"></textarea>
                    </div>
                </div>
            </div>
            <div class="row mt-2">
                <div class="col">
                    <div class="form-group">
                        <label for="exampleFormControlTextarea1">Alguna sugerencia?</label>
                        <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="extra"></textarea>
                    </div>
                </div>
            </div>
        </div>
            

                <br>
                <br>
                <button type="submit" class="btn btn-primary m-4">Enviar Solicitud</button>
            </form>

        </div>

{% endblock %}

templates/voluntarios/voluntario_home.html
{% extends 'base.html'%}


{% block content %}
<h1 class="text-center m-5 pt-5">Voluntariado</h1>
<img class="img-fluid mb-4" src="https://cflvdg.avoz.es/default/2020/01/27/00121580129357209836688/Foto/perros.jpg" alt="voluntario">
<p>Si usted es un amante de los animales y quiere brindar su apoyo para la protección de los animales de Calama, puede hacer parte  del voluntariado social por la protección y bienestar animal.</p>
<p>Este proyecto busca que los ciudadanos aporten con diferentes acciones la labor de la fundación.</p>
<p>Los voluntarios pueden acompañar labores de enseñanza y sensibilización con niños, jóvenes o familias; apoyar las campañas de adopción;  brindar un hogar de paso a animales decomisados o víctimas de maltrato o ser parte de las brigadas de salud animal.</p>
<p>Si quiere ser voluntario puede dar clic en el botón "Inscríbete como voluntario" y llenar el formulario. Luego de llenar los datos estos serán validados y una persona de la fundación lo contactará.</p>
<a class="btn btn-warning btn-lg" href="{% url 'voluntario:solicitud_voluntariado' %}">Inscríbete Como Voluntario</a>

{% endblock %}