adoption/urls.py
from django.urls import path

from . import views

app_name = 'adoption'
urlpatterns = [
    path('', views.adoption_list, name='adopcion_list'),
    path('<int:id>/', views.adoption_detail, name = 'adopcion_detail'),
    path('solicitud/<int:pet_id>/', views.solicitud_adopcion, name = 'solicitud_adopcion'),
    path('gracias-por-adoptar/', views.gracias, name='gracias'),
    path('apadrinar/<int:pet_id>/', views.apadrinar, name='apadrinar'),
]

pets/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

from django.conf.urls.static import static


from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('contacto/',views.contacto, name='contacto'),
    path('maltrato-animal/',views.maltrato, name='maltrato'),
    path('veterinarias/',views.veterinarias_list, name='veterinaria_list'),
    path('gracias/',views.gracias, name='gracias'),
    path('perfil/', include('perfil.urls', namespace='perfil')),
    path('adopcion/', include('adoption.urls', namespace='adopcion')),
    path('voluntarios/', include('voluntario.urls', namespace='voluntario')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

 

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
    <title>Hogar Canino Pulguitas {% block title %}{% endblock %} </title>
  </head>
  <body>
    <!-- include navbar -->
    {% include 'navbar.html'%}

   <div class="container-fluid">
       {% block carousel %}
       {% endblock %}
   </div>


    <div class="container">
        {% block content %}
        {% endblock %}
    </div>


    <!-- include footer -->
    {% include 'footer.html' %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>

{% block modal%}
{% endblock %}
</html>

templates/carousel.html
<div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
      <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        {% load static %}
        <img src="{% static 'images/adoption/entrenamiento_animal_bd82b34d7ffed777215098031e38a3d2.jpg' %}" class="d-block w-100" alt="...">
        <div class="carousel-caption d-none d-md-block">
          <h5>First slide label</h5>
          <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
        </div>
      </div>
      <div class="carousel-item">
        <img src="{% static 'images/adoption/1024px-Dog_retrieving_stick.jpg' %}" class="d-block w-100" alt="...">
        <div class="carousel-caption d-none d-md-block">
          <h5>Second slide label</h5>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
        </div>
      </div>
      <div class="carousel-item">
        <img src="{% static 'images/adoption/1024px-LhasaPoo3.jpg' %}" class="d-block w-100" alt="...">
        <div class="carousel-caption d-none d-md-block">
          <h5>Third slide label</h5>
          <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur.</p>
        </div>
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>

templates/contacto.html
{% extends 'base.html' %}

{% block content %}
    {% load static %}
    <h1 class="text-center text-secondary mt-4">Contacto</h1>
    <div class="contenedor-formulario">
      <div class="contenedor-imagen-contacto mb-4">
        <img src="{% static 'images/mascota-maltrato-violencia-genero.png'%}" class="img-fluid " alt="imagen de perro escondido" id='contacto-img'>
      </div>
      
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="exampleFormControlInput1">Nombres</label>
                <input type="text" class="form-control" id="exampleFormControlInput1" name="nombres" required>
            </div>
            <div class="form-group">
              <label for="exampleFormControlInput1">Email</label>
              <input type="email" class="form-control" id="exampleFormControlInput1" name="email" placeholder="name@example.com" required>
            </div>
            <div class="form-group">
                <label for="exampleFormControlInput1">Asunto</label>
                <input type="text" class="form-control" id="exampleFormControlInput1" name="asunto" required>
            </div>
            <div class="form-group">
              <label for="exampleFormControlTextarea1">Mensaje</label>
              <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="mensaje" required></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Enviar</button>
          </form>
    </div>
   
{% endblock %}

templates/footer.html
<footer>
    {% load static %}
    <div class="content footer">
        <div class="row justify-content-center">
            <div class="col-6">
                <div class="row justify-content-center text-center">
                    <div class="col-sm-3 col-md-3 col-lg-3"><a href="#"><img class="social-icon mb-3" src="{% static 'svg/008-email-1.svg' %}" alt="mail"></a></div>
                    <div class="col-sm-3 col-md-3 col-lg-3"><a href="#"><img class="social-icon mb-3" src="{% static 'svg/007-facebook-1.svg' %}" alt="facebook"></a></div>
                    <div class="col-sm-3 col-md-3 col-lg-3"><a href="#"><img class="social-icon mb-3" src="{% static 'svg/006-instagram-1.svg' %}" alt="instagram"></a></div>
                </div>
            </div>
        </div>
        <div class="row justify-content-center text-center mt-4">
            <div class="col-sm-12 col-md-12 col-lg-12">
                <h5>Hogar Canino Pulguitas 2020</h5>
            </div>
            <div class="col-sm-12 col-md-12 col-lg-12">
                <span>Creado por <a class="footer-link" href="">cavb1205</a></span>
            </div>
        </div>
    </div>
</footer>

templates/gracias.html
{% extends 'base.html' %}

{% block content %}
    {% load static %}
    
    <div class="alert alert-success mt-4" role="alert">
        <h4 class="alert-heading text-center">Gracias por escribirnos!</h4>
        <p>Hemos recibido tu mensaje, nuestro equipo evaluará los datos suministrados y nos pondremos en contacto contigo. </p>
        <hr>
        <p class="mb-0">Nuevamente te damos las gracias por querer ayudar a nuestros peludos...</p>
    </div>
    <div class="imagen text-center">
        <img src="{% static 'images/gracias.gif'%}" class="img-fluid mx-auto" alt="Responsive image">
    </div>
    
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{%load static%}

{% block carousel %}
    <!-- include carrousel -->
    {% include 'carousel.html' %}
{% endblock %}

{% block content %}
<div class="container mt-4 mb-4">
    <div class="row row-cols-1 row-cols-md-4">
        <div class="col-md-6 col-lg-3 mb-4">
          <div class="card" id='home-card-img'>
            <img src="{% static 'png/adoptar.png'%}" class="card-img-top img-fluid pt-3 m-auto" alt="perro y gato imagen animada">
            <div class="card-body">
              <h5 class="card-title text-center">Quiero Adoptar Un Peludo</h5>
              <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
              <a class = 'btn btn-info btn-lg btn-block' href="{% url 'adoption:adopcion_list'%}">Ver más</a>
            </div>
          </div>
        </div>
        <div class="col-md-6 col-lg-3 mb-4">
          <div class="card" id='home-card-img'>
            <img src="{% static 'png/donacion.png'%}" class="card-img-top img-fluid m-auto pt-3" alt="donaciones">
            <div class="card-body">
              <h5 class="card-title text-center">Quiero Donar</h5>
              <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
              <a class = 'btn btn-info btn-lg btn-block' href="">Ver más</a>
            </div>
          </div>
        </div>
        <div class="col-md-6 col-lg-3 mb-4">
          <div class="card" id='home-card-img'>
            <img src="{% static 'png/apadrinar.png'%}" class="card-img-top img-fluid pt-3 m-auto" alt="...">
            <div class="card-body">
              <h5 class="card-title text-center">Quiero Apadrinar Un Peludo</h5>
              <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content.</p>
              <a class = 'btn btn-info btn-lg btn-block' href="">Ver más</a>
            </div>
          </div>
        </div>
        <div class="col-md-6 col-lg-3 mb-4">
          <div class="card" id='home-card-img'>
            <img src="{% static 'png/voluntario.png'%}" class="card-img-top img-fluid pt-3 m-auto" alt="...">
            <div class="card-body">
              <h5 class="card-title text-center">Quiero Ser Voluntario</h5>
              <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
              <a class = 'btn btn-info btn-lg btn-block' href="{% url 'voluntario:home'%}">Ver más</a>
            </div>
          </div>
        </div>
      </div>
</div>

    

{% endblock %}

templates/maltrato.html
{% extends 'base.html' %}

{% block content %}
    {% load static %}
    <h1 class="text-center text-secondary mt-4">Maltrato hacia los animales</h1>
    <div class="contenedor-formulario">
      <div class="contenedor-imagen-contacto mb-4">
        <img src="{% static 'images/maltrato-animal.jpg'%}" class="img-fluid " alt="imagen de perro escondido" id='contacto-img'>
      </div>
        <p>La crueldad hacia los animales, también llamada crueldad animal o abuso animal, comprende comportamientos que causan dolor innecesario o estrés a los animales no humanos. Los mismos van desde la negligencia en los cuidados básicos hasta la tortura, la mutilación o la muerte intencionada</p>
        <p>Algunos tipos de maltrato son:</p>
        <ul>
            <li>Mantenerlos en instalaciones inadecuadas en función de sus hábitos.</li>
            <li>Descuidar su higiene y su salud o abandonarlos.</li>
            <li>No facilitarles alimentación adecuada para su desarrollo y el mantenimiento de su salud.</li>
            <li>Golpearlos, herirlos o mutilarlos, excepto que sea imprescindible a criterio de un veterinario.</li>
        </ul>

        <h3>Como denunciar maltrato animal en Chile?</h3>
        <p>En Chile, como en otros países, el maltrato animal por acción u omisión, las peleas de animales, así como la promoción de prácticas y espectáculos que impliquen maltrato grave, deterioro de la salud o la muerte de los animales, son conductas que son castigadas por la ley.</p>
        <p>Desde 1989, en Chile, se consideró el maltrato animal como una falta penal y según el Artículo 291 Bis del Código Penal dice que “El que cometiere actos de maltrato o crueldad con animales, será castigado con la pena de presidio menor en su grado mínimo a medio (estableciendo la pena de privación de libertad desde 61 días hasta tres años) y multa de dos a treinta unidades tributarias mensuales, o sólo con esta última”.</p>
        <p>El código penal también castiga la ausencia de suministros en alimento y agua, el empleo de instrumentos o sustancias que provoquen a los animales sufrimiento o muerte. Al igual que la remoción, destrucción o alteración de cualquier miembro, órgano o apéndice del animal que por causas distintas a las propiamente veterinarias, sanitarias u otras expresamente autorizadas por la ley.</p>

        <h4>¿Cómo denunciar?</h4>
        <p>El maltrato animal puede ser denunciado por cualquier persona bajo el modelo de querella criminal, un escrito judicial que debe hacerse ante el Ministerio Público (Fiscalía local del lugar en donde se ha cometido el acto de maltrato), con los carabineros puedes denunciar llamando al teléfono 133, o con Brigadas Investigadoras de Delitos Contra el Medio Ambiente (BIDEMA), o a través de una querella en los tribunales de justicia a nivel nacional.</p>

        <p>Pasos para interponer la denuncia</p>

        <ol>
            <li><strong> Recopile la información:</strong>
                <p>Debes tener en cuenta los siguientes criterios.</p>
                <p>A. Narración verídica con la mayor información del hecho de maltrato en donde se incluya la fecha exacta (día y hora), así como el lugar en donde ocurrió el hecho (calle, intersección de calles, numeración, comuna).</p>
                <p>B. Datos básicos del autor del hecho de maltrato, información como nombre completo, dirección de residencia, nombres de testigos que puedan dar fe del hecho, estos pueden ser útiles en el momento de realizar su denuncia.</p>
                <p>C. Será de gran ayuda si puedes registrar los hechos por medio de fotografías o material audiovisual que funcionen como prueba del maltrato.</p>
                <p>D. Debes adjuntar una evaluación o diagnóstico de un Médico Veterinario, que documente por medio de un informe médico la condición corporal, las lesiones, heridas o traumas provocadas por la agresión y si es el caso el registro de posibles golpes con objetos contundentes, uso de elementos cortopunzantes, etc., con su debido pronóstico, evolución y tratamiento. De haber terminado en muerte el acto de maltrato, se debe adjuntar un informe de necropsia que de cuenta de las causas claras de la defunción del animal.</p>
            </li>
            <li>
                <strong>Encuentre la oficina del ente más cercano:</strong>
                <p>Puedes comunicarte con alguna de las entidades donde puedes interponer la denuncia, para que te informen cual es la oficina más cercana a tu residencia.</p> 
                <p>También puedes escribir a los correos bidema@investigaciones.cl y analisis.bidema@investigaciones.cl de la Brigada Investigadora de Delitos Contra el Medio Ambiente y Patrimonio (BIDEMA).</p>
           
            </li>
            <li>
                <strong>Realice la denuncia:</strong>
                <p>Una vez que identificó la fiscalía, comisaría o oficina de BIDEMA más cercana, puede ir a interponer su denuncia con todas las pruebas y documentos que recopiló.</p>
            </li>
            <li>
                <strong>¿Qué pasa después de interpuesta la denuncia?</strong>
                <p>Una vez interpuesta la denuncia, ante una de las tres entidades mencionadas, sólo al fiscal corresponde la calificación jurídica del hecho, es decir, analizar si el hecho califica o no como delito, y establecer el tipo específico de delito, definir si hay responsabilidad penal del denunciado, determinar si la acción penal se encuentra, o no, prescrita por el paso del tiempo.</p>
                <p>Una vez ingresada la denuncia a la fiscalía se le asigna un número denominado Rol Único de Causa (RUC). Con este número, el denunciante, puede hacer el seguimiento a la denuncia. Además, el denunciante será llamado por la fiscalía o BIDEMA a prestar declaración, la cual será consignada en un acta leída y firmada –conforme- por el denunciante.</p>
            </li>
        </ol>

        <div class="alert alert-warning" role="alert">
            Si deseas denunciar o solicitar asesoria sobre casos de maltrato por favor déjanos tus datos en el siguiente formulario, serás contactado por una persona de la fundación.
        </div>
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="exampleFormControlInput1">Nombres</label>
                <input type="text" class="form-control" id="exampleFormControlInput1" name="nombres" required>
            </div>
            <div class="form-group">
                <label for="exampleFormControlInput1">Teléfono de contacto</label>
                <input type="text" class="form-control" id="exampleFormControlInput1" name="telefono" required>
            </div>
            <div class="form-group">
              <label for="exampleFormControlInput1">Email</label>
              <input type="email" class="form-control" id="exampleFormControlInput1" name="email" placeholder="name@example.com" required>
            </div>
            <div class="form-group">
                <label for="exampleFormControlInput1">Asunto</label>
                <input type="text" class="form-control" id="exampleFormControlInput1" name="asunto" required>
            </div>
            <div class="form-group">
              <label for="exampleFormControlTextarea1">Mensaje</label>
              <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="mensaje" required></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Enviar</button>
          </form>
    </div>
   
{% endblock %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
    <a class="navbar-brand" href="/">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse mr-4" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/">Inicio <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Sobre Nosotros
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">Action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Another action</a>
          </div>
        </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Participa
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'adoption:adopcion_list'%}">Adopta</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Donaciones</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Padrinos</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Socios</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'voluntario:home'%}">Voluntarios</a>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Eventos<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Información Importante
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'contacto'%}">Contacto<span class="sr-only">(current)</span></a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'maltrato'%}">Maltrato animal</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Animales perdidos</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Documentos informativos</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'veterinaria_list' %}">Directorio veterinarias</a>
              
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">{% if user.is_authenticated %}Hola, {{ user.first_name }}{% else%} Login {% endif %}<span class="sr-only">(current)</span></a>
          </li>
      </ul>
    </div>
  </nav>

templates/veterinaria_list.html
{% extends 'base.html'%}

{% block content %}
    <h1 class="text-center m-5">Veterinarias Disponibles</h1>
    <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 mt-5">
        {% for veterinaria in veterinarias %}
            <div class="col mb-4">
              <div class="card">
                <img src="/media/{{veterinaria.imagen}}" class="card-img-top rounted" alt="{{veterinaria.nombre}}">
                <div class="card-body">
                  <h5 class="card-title">{{veterinaria.nombre|title}}</h5>
                  <p class="card-text">Dirección: {{veterinaria.direccion}}</p>
                  <p class="card-text">Teléfonos: {{veterinaria.telefonos}}</p>
                  <p class="card-text">Horarios de atención: {{veterinaria.horarios}}</p>
                </div>
              </div>
            </div>
        {% endfor %}
    </div>

{% endblock %}